# Generated by Django 4.2.23 on 2025-08-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageManager', '0002_uploadedimage_details_uploadedimage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='name',
        ),
    ]
